### ISSUE TITLE
Some ranges return no value

### ISSUE THREAD

**Issue by t00fan** [iStroml/IVChartBot#1]
When I try to enter a range of 90-100% , it returns no value.  Is this because there are too many combinations?

This is the error  I see

Traceback (most recent call last):
  File "/home/.local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/home/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: BAD REQUEST (status code: 400)

**Comment by t00fan** [comment]
This appears to be because of the discord 2000 character limit.  Would it possible to split messages over 2000 characters into multiple ones?

**Comment by iStroml** [comment]
@t00fan Hi, thanks for the issue. Sorry I've not worked at this project for a few months. I'm aware of this problem and gonna fix it in the next few days. Thanks for the patience.
